image: viaduck/ci
services:
    - mariadb:latest
    
variables:
    GIT_SUBMODULE_STRATEGY: recursive
    MYSQL_DATABASE: "mariadbpptest"
    MYSQL_USER: "test"
    MYSQL_PASSWORD: "test"
    MYSQL_RANDOM_ROOT_PASSWORD: "true"            # it's not used anyway

stages:
    - build         # contains build and test and deploy

test:
    script:
        - mkdir build
        - cd build
        - cmake ../ -DMARIADBPP_DOC=ON -DMARIADBPP_TEST=ON -DTEST_HOSTNAME=mariadb -DTEST_USERNAME=$MYSQL_USER -DTEST_PASSWORD=$MYSQL_PASSWORD -DTEST_PORT=3306 -DTEST_DATABASE=$MYSQL_DATABASE -DGTEST_SRC_DIR=/usr/src/googletest/
        - make
        - test/mariadbpp_tests             # runs gtest target
        - cmake . -DCMAKE_BUILD_TYPE=Debug
        - make mariadbpp_coverage             # generate code coverage report
        - make mariadbpp_doc                  # generate doxygen code documentation
    stage: build
    artifacts:
        paths:
        - build/test/coverage/           # coverage data
        - build/doc/html/                # doxygen documentation
